# Generated by Django 5.1.4 on 2025-07-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]
