# Generated by Django 5.1.4 on 2025-07-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('id_type', models.CharField(choices=[('Student ID', 'Student ID'), ('National ID', 'National ID'), ('Passport', 'Passport'), ("Driver's License", "Driver's License"), ('Other', 'Other')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('is_student', models.BooleanField(default=False)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('year_of_study', models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('Graduate', 'Graduate'), ('Postgraduate', 'Postgraduate')], max_length=20)),
                ('transportation_mode', models.CharField(choices=[('Walking', 'Walking (for short distances)'), ('Bicycle', 'Bicycle'), ('Motorcycle/Bodaboda', 'Motorcycle/Bodaboda'), ('Car', 'Car'), ('Scooter', 'Scooter')], max_length=30)),
                ('available_hours', models.CharField(choices=[('5-10 hours', '5-10 hours'), ('10-15 hours', '10-15 hours'), ('15-20 hours', '15-20 hours'), ('20+ hours', '20+ hours')], max_length=20)),
                ('has_license', models.BooleanField(default=False)),
                ('emergency_contact', models.CharField(blank=True, max_length=150)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('motivation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
