# Generated by Django 5.1.4 on 2025-07-22 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deliveryapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='deliveryapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='deliveryapplication',
            name='phone',
        ),
        migrations.AddField(
            model_name='deliveryapplication',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_application', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
