# Generated by Django 5.1.4 on 2025-07-23 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_deliveryapplication_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryschedule',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RenameField(
            model_name='deliveryschedule',
            old_name='scheduled_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='deliveryschedule',
            old_name='scheduled_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='deliveryschedule',
            old_name='additional_info',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='deliveryschedule',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryschedule',
            name='schedule_type',
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='delivery_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='start_time',
            field=models.TimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryapplication',
            name='id_number',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.CreateModel(
            name='DeliveryPersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('truck', 'Truck')], max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(default='bank', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('max_delivery_distance', models.IntegerField(default=10)),
                ('preferred_areas', models.TextField(blank=True, help_text='Comma-separated list of preferred areas')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='delivery_profiles/')),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('notify_schedule_reminders', models.BooleanField(default=True)),
                ('notify_earnings_updates', models.BooleanField(default=True)),
                ('notify_rating_alerts', models.BooleanField(default=True)),
                ('auto_accept_orders', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EarningsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('delivery', 'Delivery'), ('bonus', 'Bonus'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='delivery.delivery')),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
