# Generated by Django 4.2 on 2025-07-02 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_product_subcategory_alter_product_type_and_more"),
        ("products", "0003_add_sample_categories"),
    ]

    operations = []
