# Generated by Django 5.1.4 on 2025-07-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20250701_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailimages',
            field=models.ImageField(blank=True, null=True, upload_to='products/detailimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20),
        ),
    ]
