# Generated by Django 5.1.4 on 2025-07-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_detailimages_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detailimages',
        ),
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/detail_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='products.product')),
            ],
        ),
    ]
