# Generated by Django 5.2.4 on 2025-07-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='Transaction reference (e.g., Paystack or M-Pesa code)', max_length=100, null=True, unique=True),
        ),
    ]
